webapp/codes/conf/urls.py
from django.conf.urls import include, url,patterns
from django.contrib import admin
import audiotracks

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # Examples:
    # url(r'^$', 'musicapps.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'website.views.index', name='index'),
    url(r'^tuneaudit/', include('tuneaudit.urls', namespace="tuneaudit")),
    url(r'^tuneaudit/', include('registration.urls',namespace="registration")),
    url(r'^tuneaudit/', include('website.urls', namespace="website")),
    url(r'^tuneaudit/', include('tracks.urls', namespace="tracks")),
    #url(r'^tuneaudit/', include('audiotracks.urls', namespace="audiotracks")),
    url(r'^admin/', include(admin.site.urls)),

    url("^music", include("audiotracks.urls")),
    url("^(?P<username>[\w\._-]+)/music", include("audiotracks.urls")),
]

if not settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

webapp/codes/modules/tracks/urls.py
from django.conf.urls import patterns, include, url

from django.views.generic.base import TemplateView

from . import views


from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns('',
    url(r'^musichome/$', views.index, name="home"),
    
    
    
)

if settings.DEBUG:
    urlpatterns += patterns('',
            (r'^media/(?P<path>.*)$', 'django.views.static.serve', 
                {'document_root': settings.MEDIA_ROOT}),)
    urlpatterns += staticfiles_urlpatterns()




webapp/codes/modules/website/urls.py
from django.conf.urls import patterns, include, url

from django.views.generic.base import TemplateView

from . import views

from views import DisplayRes,DisplayHome,DisplaySorry


from django.contrib import admin
admin.autodiscover()






urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^loggedout/$', views.logout_view, name='logoutview'),
    #url(r'^tunes/$', views.get_tunes, name='tunesview'),
    #url(r'^login/$', views.ta_login, name='loginview'),
    #url(r'^emailentry/$', views.ta_email, name='emailview'),
    url(r'^restricted/', views.home, name='homepage'),
    #url(r'^login/1$', views.ta_login, name='loginview'),


    
    
    

    url(r'^name/$', views.get_name, name='nameview'),

    url(r'^thanks/$', DisplayRes.as_view()),
    url(r'^home/$', DisplayHome.as_view(),name='home'),
    url(r'^sorry/$', DisplaySorry.as_view()),

    #url(r'^user/password/', include(password_change_patterns)),


    #LOGIN
    url(r'^login/$', 'django.contrib.auth.views.login',name="my_login"),


    #--------------------------password reset ---------------------------#
    url(r'^user/password/reset/$', 'django.contrib.auth.views.password_reset', 
        {'post_reset_redirect' : '/tuneaudit/user/password/reset/done/'},
        name='password_reset'),

    url(r'^user/password/reset/done/$',
        'django.contrib.auth.views.password_reset_done'),

    url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'registration/password_reset_confirm.html',
        'post_reset_redirect' : '/tuneaudit/user/password/done/'},
        name='password_reset_confirm'),

   
    url(r'^user/password/done/$', 
        'django.contrib.auth.views.password_reset_complete'),




    

]






webapp/codes/modules/tracks/models.py
import datetime

from django.db import models

from django.utils import timezone

from django.forms import ModelForm

from django.contrib.auth.models import User




#-------------------------------------------------------------------------------------------------------

webapp/codes/modules/tracks/views.py
from django.shortcuts import render_to_response,render
from django.template import RequestContext


def index(request):
    
    return render(request, 'tracks/index.html')

webapp/codes/modules/tracks/templates/tracks/base.html
{% load i18n %} 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>django-audiotracks example project</title>
    <style>
      label { display: block; }
      .audiotracks-edit-row { clear:both; margin-bottom: 1em; }
      .audiotracks-edit-row > div { float: left; margin-right: 1em; }
      .audiotracks-form { margin-bottom: 1em; }
      .audiotracks-delete-image-label { display: inline; }
      .messages { color: green; border: solid 1px green; padding: 0.2em; }
      .messages li { list-style: none; }
      .errorlist { color: red; list-style: none; display: inline; }
    </style>
    {% block extra_head %}{% endblock %}
  </head>
  <body>

  {% block subnav %}
      {% if user.is_authenticated %}
          <ul>
            <li><a href="{% url 'audiotracks' %}">{% trans 'Latest tracks' %}</a></li>
            <li><a href="{% url 'user_index' user.username %}">{% trans 'Your tracks' %}</a></li>
            <li><a href="{% url 'upload_track' %}">{% trans 'Upload track' %}</a></li>
          </ul>
      {% else %}
          &nbsp;
      {% endif %}
  {% endblock %}

  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}

  {% block body %}{% endblock %}
  {% block extra_body %}{% endblock %}
  </body>
</html>

webapp/codes/modules/tracks/templates/tracks/base_2.html
{% load i18n %} 
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>django-audiotracks example - {% block title %}Homepage{% endblock %}</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    <link rel="stylesheet" href="{% static 'tracks/css/bootstrap-2.0.css' %}">
    <link rel="stylesheet" href="{% static 'tracks/css/style.css' %}"> 
    {% block extra_head %}{% endblock %}
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="#">django-audiotracks demo</a>
          <ul class="nav">
            <li class="active"><a href="{% url 'tracks:home' %}">Home</a></li>
            <li><a href="{% url 'audiotracks' %}">Audio tracks</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'user_index' user.username %}">{% trans 'Your tracks' %}</a></li>
                <li><a href="{% url 'upload_track' %}">{% trans 'Upload track' %}</a></li>
                {% if user.is_staff %}<li><a href="/admin">Admin</a></li>{% endif %}
                <li><a href="{% url 'website:logoutview' %}">Logout</a></li>
            {% endif %}
          </ul>
          {% if not user.is_authenticated %}
          <form action="{% url 'website:my_login' %}" class="navbar-form pull-right" method="post">
            {% csrf_token %}
            <input class="input-small" type="text" name="username" placeholder="Username">
            <input class="input-small" type="password" name="password" placeholder="Password">
            <button class="btn" type="submit">Sign in</button>
          </form>
          {% endif %}
        </div>
      </div>
    </div>

    <div class="container">

      <div class="content">
        {% block body %}{% endblock %}
        {% block extra_body %}{% endblock %}
      </div>

      <footer>
        <p>&copy; Company 2011</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

webapp/codes/modules/tracks/templates/tracks/index.html
{% extends 'tracks/base_2.html' %}


{% block body %}
<p>
  This is a sample project for django-audiotracks
</p>
<ul>
  <li><a href="{% url 'audiotracks' %}">Go to audio tracks</a></li>
</ul>
{% endblock %}