webapp/codes/conf/urls.py
from django.conf.urls import include, url,patterns
from django.contrib import admin
import audiotracks

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # Examples:
    # url(r'^$', 'musicapps.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'website.views.index', name='index'),
    url(r'^tuneaudit/', include('tuneaudit.urls', namespace="tuneaudit")),
    url(r'^tuneaudit/', include('registration.urls',namespace="registration")),
    url(r'^tuneaudit/', include('website.urls', namespace="website")),
    url(r'^tuneaudit/', include('tracks.urls', namespace="tracks")),
    #url(r'^tuneaudit/', include('audiotracks.urls', namespace="audiotracks")),
    url(r'^admin/', include(admin.site.urls)),

    url("^music", include("audiotracks.urls")),
    url("^(?P<username>[\w\._-]+)/music", include("audiotracks.urls")),
]

if not settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

webapp/codes/modules/tracks/urls.py
from django.conf.urls import patterns, include, url

from django.views.generic.base import TemplateView

from . import views


from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns('',
    url(r'^musichome/$', views.index, name="home"),
    
    
    
)

if settings.DEBUG:
    urlpatterns += patterns('',
            (r'^media/(?P<path>.*)$', 'django.views.static.serve', 
                {'document_root': settings.MEDIA_ROOT}),)
    urlpatterns += staticfiles_urlpatterns()




webapp/codes/modules/website/urls.py
from django.conf.urls import patterns, include, url

from django.views.generic.base import TemplateView

from . import views

from views import DisplayRes,DisplayHome,DisplaySorry


from django.contrib import admin
admin.autodiscover()






urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^loggedout/$', views.logout_view, name='logoutview'),
    #url(r'^tunes/$', views.get_tunes, name='tunesview'),
    #url(r'^login/$', views.ta_login, name='loginview'),
    #url(r'^emailentry/$', views.ta_email, name='emailview'),
    url(r'^restricted/', views.home, name='homepage'),
    #url(r'^login/1$', views.ta_login, name='loginview'),


    
    
    

    url(r'^name/$', views.get_name, name='nameview'),

    url(r'^thanks/$', DisplayRes.as_view()),
    url(r'^home/$', DisplayHome.as_view(),name='home'),
    url(r'^sorry/$', DisplaySorry.as_view()),

    #url(r'^user/password/', include(password_change_patterns)),


    #LOGIN
    url(r'^login/$', 'django.contrib.auth.views.login',name="my_login"),


    #--------------------------password reset ---------------------------#
    url(r'^user/password/reset/$', 'django.contrib.auth.views.password_reset', 
        {'post_reset_redirect' : '/tuneaudit/user/password/reset/done/'},
        name='password_reset'),

    url(r'^user/password/reset/done/$',
        'django.contrib.auth.views.password_reset_done'),

    url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'registration/password_reset_confirm.html',
        'post_reset_redirect' : '/tuneaudit/user/password/done/'},
        name='password_reset_confirm'),

   
    url(r'^user/password/done/$', 
        'django.contrib.auth.views.password_reset_complete'),




    

]






webapp/codes/modules/tracks/models.py
import datetime

from django.db import models

from django.utils import timezone

from django.forms import ModelForm

from django.contrib.auth.models import User




#-------------------------------------------------------------------------------------------------------

webapp/codes/modules/website/models.py
import datetime

from django.db import models

from django.utils import timezone

from django.forms import ModelForm

from django.contrib.auth.models import User




# Create your models here.
class Genre(models.Model):
    genre_name = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __unicode__(self):              # __unicode__ on Python 2
        return self.genre_name
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'      



    def test_was_published_recently_with_old_pubdate(self):
        """
        was_published_recently() should return False for questions whose
        pub_date is older than 1 day.
        """
        time = timezone.now() - datetime.timedelta(days=30)
        old_genre = Genre(pub_date=time)
        self.assertEqual(old_genre.was_published_recently(), False)

    def test_was_published_recently_with_recent_pubdate(self):
        """
        was_published_recently() should return True for questions whose
        pub_date is within the last day.
        """
        time = timezone.now() - datetime.timedelta(hours=1)
        recent_genre = Genre(pub_date=time)
        self.assertEqual(recent_genre.was_published_recently(), True)  


class Choice(models.Model):
    genre = models.ForeignKey(Genre)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):              # __unicode__ on Python 2
        return self.choice_text





#TUNE AUDIT MODELS.
#-------------------------------------------------------------------------------------------------------
class TuneAuditUser(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    nickname = models.CharField(max_length=50)
    email = models.EmailField()
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    
    def __unicode__(self):              # __unicode__ on Python 2
        return self.firstname

#-------------------------------------------------------------------------------------------------------





webapp/codes/modules/tracks/views.py
from django.shortcuts import render_to_response,render
from django.template import RequestContext


def index(request):
    
    return render(request, 'tracks/index.html')

webapp/codes/modules/tracks/templates/audiotracks/_list_actions.html
{% load i18n %}
  <a class="btn small btn-primary" href="{% url 'edit_track' track.id %}">{% trans 'Edit' %}</a>
  <a class="btn small btn-danger" href="{% url 'confirm_delete_track' track.id %}">{% trans 'Delete' %}</a>


webapp/codes/modules/tracks/templates/audiotracks/base.html
{% load staticfiles %}
{% load i18n %} 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>django-audiotracks example project</title>


    <meta charset="utf-8">
    <!-- Title here -->
    <title>{% block title %}Tune Audit{% endblock %}</title>




    <!-- Description, Keywords and Author -->
    <meta name="description" content="Your description">
    <meta name="keywords" content="Your,Keywords">
    <meta name="author" content="ResponsiveWebInc">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Styles -->
    <!-- Bootstrap CSS -->
    <link href="{% static 'tuneaudit/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Slider CSS -->
    <link href="{% static 'tuneaudit/css/slider.css' %}" rel="stylesheet">
    <!-- Pretty Photo -->
    <link href="{% static 'tuneaudit/css/prettyPhoto.css' %}" rel="stylesheet">
    <!-- Font awesome CSS -->
    <link href="{% static 'tuneaudit/css/font-awesome.min.css' %}" rel="stylesheet">    
    <!-- Custom CSS -->
    <link href="{% static 'tuneaudit/css/style.css' %}" rel="stylesheet">
    <!-- Color Stylesheet - orange, blue, pink, brown, red or green-->
    <link href="{% static 'tuneaudit/css/green.css' %}" rel="stylesheet"> 

     <link href="{% static 'tuneaudit/css/mystyle.css' %}" rel="stylesheet"> 
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'tuneaudit/img/favicon/favicon.png' %}">


  





    <style>
      label { display: block; }
      .audiotracks-edit-row { clear:both; margin-bottom: 1em; }
      .audiotracks-edit-row > div { float: left; margin-right: 1em; }
      .audiotracks-form { margin-bottom: 1em; }
      .audiotracks-delete-image-label { display: inline; }
      .messages { color: green; border: solid 1px green; padding: 0.2em; }
      .messages li { list-style: none; }
      .errorlist { color: red; list-style: none; display: inline; }
    </style>
    {% block extra_head %}{% endblock %}
  </head>
  <body>
    <!-- Header starts -->

<header>
   <div class="container">
      <div class="row">
         <div class="col-md-4 col-sm-4">
            <!-- Logo and site link -->
            <div class="logo">
               <h1><a href="{% url 'website:index' %}">Tune Audit<span class="color">.</span></a></h1>
            </div>
         </div>
         <div class="col-md-4 col-sm-4 col-sm-offset-4 col-md-offset-4">
            <div class="list">
               <!-- Add your phone number here -->
               <div class="phone">
                  <i class="fa fa-phone"></i> Phone: 233-71793508
               </div>
               <hr />
               <!-- Add your email id here -->
               <div class="email">
                  <i class="fa fa-envelope-o"></i> Email: enquiries@tuneaudit.com
               </div>
               <hr />
               <!-- Add your address here -->
               <div class="address">
                  <i class="fa fa-home"></i> Address: 12, Srtington Street, NY
               </div>
            </div>
         </div>
      </div>
   </div>
</header>



{% block navigation %}
<!-- Navigation Starts -->
    <!-- Note down the syntax before editing. It is the default twitter bootstrap navigation -->
    <div class="navbar bs-docs-nav" role="banner">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
        <!-- Navigation links starts here -->
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="{% url 'website:index' %}" class="da-link"> Home</a>
            </li>
            <!-- Navigation with sub menu. Please note down the syntax before you need. Each and every link is important. -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages #1 <b class="caret"></b></a>
              <!-- Submenus -->
              <ul class="dropdown-menu">
                <li><a href="support.html">Support</a></li>
                <li><a href="products.html">Products</a></li>
                <li><a href="register.html">Register</a></li>
                <li><a href="login.html">Login</a></li>                  
                <li><a href="about.html">About</a></li>
                <li><a href="service.html">Service #1</a></li>
                <li><a href="service1.html">Service #2</a></li>
                <li><a href="pricing.html">Pricing Table</a></li>
                <li><a href="careers.html">Careers</a></li>
                <li><a href="faq.html">FAQ</a></li>
                <li><a href="team.html">Team</a></li>
              </ul>
            </li>   
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages #2 <b class="caret"></b></a>
              <!-- Submenus -->
              <ul class="dropdown-menu">
                <li><a href="404.html">404</a></li>
                <li><a href="comingsoon.html">Coming Soon</a></li>
                <li><a href="resume.html">Resume</a></li>
                <li><a href="sitemap.html">Sitemap</a></li>
                <li><a href="process.html">Process</a></li>
                <li><a href="testimonials.html">Testimonials</a></li>
                <li><a href="review.html">Review</a></li>
                <li><a href="project.html">Project</a></li>
                <li><a href="timeline.html">Timeline</a></li>
                <li><a href="full-width.html">Full Width</a></li>
                <li><a href="events.html">Events</a></li>
              </ul>
            </li>   
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
              <!-- Submenus -->
              <ul class="dropdown-menu">
                <li><a href="blog.html">Blog Main #1</a></li>
                <li><a href="blog1.html">Blog Main #2</a></li>
                <li><a href="blog2.html">Blog Main #3</a></li>
                <li><a href="blog-ls.html">Blog Left Sidebar</a></li>
                <li><a href="blog-ns.html">Blog No Sidebar</a></li>                  
                <li><a href="blog-single.html">Blog Single</a></li>
              </ul>
            </li>  
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Features <b class="caret"></b></a>
              <!-- Submenus -->
              <ul class="dropdown-menu">
                <li><a href="features.html">Features #1</a></li>
                <li><a href="features1.html">Features #2</a></li>
                <li><a href="features2.html">Features #3</a></li>
              </ul>
            </li>   
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
              <!-- Submenus -->
              <ul class="dropdown-menu">
                <li><a href="gallery.html">Gallery</a></li>
                <li><a href="portfolio1.html">Portfolio #1</a></li>
                <li><a href="portfolio2.html">Portfolio #2</a></li>
                <li><a href="portfolio.html">Portfolio #3</a></li>
              </ul>
            </li> 
              
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Contact <b class="caret"></b></a>
              <!-- Submenus -->
              <ul class="dropdown-menu">
                <li><a href="contact.html">Contact #1</a></li>
                <li><a href="contact1.html">Contact #2</a></li>
                <li><a href="clients.html">Clients</a></li>
              </ul>
            </li> 
           {% if user.is_authenticated %}
            <li class="dropdown">
              <a href="{% url 'website:logoutview' %}">Logout</a>
              
            </li> 
            {% else %}
         
      {% endif %}
            
            
          </ul>
        </nav>
      </div>
    </div>
    <!--/ Navigation Ends -->   
    
 {% endblock %}



            <div class="main-content">
{% block content %}


    

 {% endblock %}
            </div>


              <!-- Clients starts -->
               
            <div class="row">
               <div class="col-md-12">
                  <div class="clients">
             <img class="img-responsive" src="{% static 'tuneaudit/img/clients/1.png' %}" alt="" />
             <img class="img-responsive" src="{% static 'tuneaudit/img/clients/2.png' %}" alt="" />
             <img class="img-responsive" src="{% static 'tuneaudit/img/clients/3.png' %}" alt="" />
             <img class="img-responsive" src="{% static 'tuneaudit/img/clients/4.png' %}" alt="" />
             <img class="img-responsive" src="{% static 'tuneaudit/img/clients/5.png' %}" alt="" />
             <img class="img-responsive" src="{% static 'tuneaudit/img/clients/6.png' %}" alt="" />
                  </div>
               </div>
            </div>
            
            <!-- Clients ends -->


<!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
          <!-- Widget 1 -->
          <div class="widget">
            <h4>About Us</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras elementum dolor eget nisi fermentum quis hendrerit magna vestibulum. </p>
            <!-- Social Media -->
            <div class="social">
              <a href="#"><i class="fa fa-twitter twitter"></i></a>
              <a href="#"><i class="fa fa-pinterest pinterest"></i></a>
              <a href="#"><i class="fa fa-facebook facebook"></i></a>
              <a href="#"><i class="fa fa-google-plus google-plus"></i></a>
              <a href="#"><i class="fa fa-linkedin linkedin"></i></a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
         <!-- widget 2 -->
         <div class="widget">
          <h4>Recent Posts</h4>
             <ul>
              <li><i class="fa fa-angle-right"></i> <a href="#">Sed eu leo orci, in rhoncus puru</a></li>
              <li><i class="fa fa-angle-right"></i> <a href="#">Condimentum gravida metus</a></li>
              <li><i class="fa fa-angle-right"></i> <a href="#">Lpsum, in rhoncus purus</a></li>
              <li><i class="fa fa-angle-right"></i> <a href="#">Etiam at in rhoncus puru nul</a></li>
              <li><i class="fa fa-angle-right"></i> <a href="#">Fusce vel magnais dapibus facilisis</a></li>
             </ul>
         </div>
        </div>
        <div class="col-md-4">
         <!-- Widget 3 -->
         <div class="widget">
          <h4>Categories</h4>
          <ul>
             <li><i class="fa fa-angle-right"></i> <a href="#">Condimentum</a></li>
             <li><i class="fa fa-angle-right"></i> <a href="#">Etiam at</a></li>
             <li><i class="fa fa-angle-right"></i> <a href="#">Fusce vel</a></li>
             <li><i class="fa fa-angle-right"></i> <a href="#">Vivamus</a></li>
             <li><i class="fa fa-angle-right"></i> <a href="#">Pellentesque</a></li>
          </ul>
         </div>
        </div>
       </div>
       <div class="row">
        <hr />
        <div class="col-md-12"><p class="copy pull-left">
        <!-- Copyright information. You can remove my site link. -->
             Copyright &copy; <a href="#">Your Site</a> | Designed by <a href="http://responsivewebinc.com">Responsive Web Design</a></p></div>
      </div>
      </div>
    </footer>   
    <!--/ Footer -->
  
    <!-- Scroll to top -->
    <span class="totop"><a href="#"><i class="fa fa-angle-up"></i></a></span> 
      
    <!-- Javascript files -->
    <!-- jQuery -->
    <script src="{% static 'tuneaudit/js/jquery.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'tuneaudit/js/bootstrap.min.js' %}"></script>
    <!-- Isotope, Pretty Photo JS -->
    <script src="{% static 'tuneaudit/js/jquery.isotope.js' %}"></script>
    <script src="{% static 'tuneaudit/js/jquery.prettyPhoto.js' %}"></script>
    <!-- Support Page Filter JS -->
    <script src="{% static 'tuneaudit/js/filter.js' %}"></script>
    <!-- C Slider JS -->
    <script src="{% static 'tuneaudit/js/jquery.cslider.js' %}"></script>
    <script src="{% static 'tuneaudit/js/modernizr.custom.28468.js' %} "></script>
    <!-- Respond JS for IE8 -->
    <script src="{% static 'tuneaudit/js/respond.min.js' %}"></script>
    <!-- HTML5 Support for IE -->
    <script src="{% static 'tuneaudit/js/html5shiv.js' %}"></script>
    <!-- Custom JS -->
    <script src="{% static 'tuneaudit/js/custom.js' %}"></script>
    <script>
      $(function() {
      
        $('#da-slider').cslider({
          autoplay  : true,
          interval : 6000
        });
      
      });
    </script>


  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}

  {% block body %}{% endblock %}
  {% block extra_body %}{% endblock %}
  </body>
</html>





webapp/codes/modules/tracks/templates/audiotracks/confirm_delete.html
{% extends "audiotracks/base.html" %}
{% load i18n %}

{% block content %}
{% if user.is_authenticated %}
<div class="audiotracks-form">
  <p>
  {% blocktrans with track.title as title %}Are you sure you want to delete "{{ title }}"? This can't be undone.{% endblocktrans %}
  </p>
  <form method="POST" action="{% url 'delete_track' %}">
    {% csrf_token %}
    <input type="hidden" name="track_id" value="{{ track.id }}">
    <input type="hidden" name="came_from" value="{{ came_from }}">
    <button class="btn btn-danger">{% trans 'Yes, delete this track' %}</button>
  </form>
</div>
{% endif %}
{% endblock %}

webapp/codes/modules/tracks/templates/audiotracks/detail.html
{% extends "audiotracks/mediaelement_base.html" %}
{% load i18n %}

{% block content %}
<div class="audiotracks-detail js-audiotracks-container" align="center">
  {% if track.image %}
  <img src="{{ track.image.url_200x200 }}" />
  {% endif %}
  {% include "audiotracks/listing_item.html" %}
  {% if track.description %}
  <div class="audiotracks-description">
    {{ track.description }}
  </div>
  {% endif %}
  <div class="audiotracks-download">
    <a class="btn btn-large btn-success" href="{{ track.audio_file.url }}">
      {% blocktrans with size=track.audio_file.size|filesizeformat  type=track.filetype %}
      Download {{ type }} file ({{size}})
      {% endblocktrans %}
    </a>
  </div>
{% if track.user == request.user %}
<p>
  <a class="btn btn-primary" href="{% url 'edit_track' track.id %}">{% trans 'Edit' %}</a>
  <a class="btn btn-danger" href="{% url 'confirm_delete_track' track.id %}">{% trans 'Delete' %}</a>
</p>
{% endif %}
</div>
{% endblock %}

webapp/codes/modules/tracks/templates/audiotracks/edit.html
{% extends "audiotracks/base.html" %}
{% load i18n %}

{% block content %}
{% if user.is_authenticated %}
<div class="audiotracks-form" align="center">

  <form class="form-stacked" method="POST" enctype="multipart/form-data" 
    action="{% url 'edit_track' track.id %}">
    {% csrf_token %}
    <fieldset>
      <legend>{% trans 'Edit track' %}</legend>
      {{ form.non_field_errors }}
      <div class="audiotracks-edit-row">
        {{ form.audio_file.errors }}
        <label class="top" for="id_audio_file">{{ form.audio_file.label }}</label>
        {{ form.audio_file }}
        <span class="audiotracks-edit-current-data">{{ track_filename }}</span>
      </div>
      <div class="audiotracks-edit-row">
        {{ form.image.errors }}
        <label class="top" for="id_image">{{ form.image.label }}</label>
        {{ form.image }}
        {% if track.image %}
          <img src="{{ track.image.url_48x48 }}" alt="Track image">
          <input type="checkbox" name="delete_image" value="1"
          id="delete_image">
          <label id="audiotracks-delete-image-label" for="delete_image">{% trans 'Delete image' %}</label>
        {% endif %}
      </div>
      <div class="audiotracks-edit-row" style="margin-left:40%">
        <div class="audiotracks-edit-half-row">
          {{ form.title.errors }}
          <label for="id_title">{{ form.title.label }}</label>
          {{ form.title }}
        </div>
        <div class="audiotracks-edit-half-row">
          {{ form.artist.errors }}
          <label for="id_artist">{{ form.artist.label }}</label>
          {{ form.artist }}
        </div>
      </div>
      <div class="audiotracks-edit-row" style="margin-left:40%">
        <div class="audiotracks-edit-half-row">
          {{ form.genre.errors }}
          <label for="id_genre">{{ form.genre.label }}</label>
          {{ form.genre }}
        </div>
        <div class="audiotracks-edit-half-row">
          {{ form.date.errors }}
          <label for="id_date">{{ form.date.label }}</label>
          {{ form.date }}
        </div>
      </div>
      <div class="audiotracks-edit-row" >
        {{ form.tags.errors }}
        <label for="id_tags">{{ form.tags.label }}</label>
        {{ form.tags }}
      </div>
      <div class="audiotracks-edit-row">
        {{ form.description.errors }}
        <label class="top" for="id_description">{{ form.description.label }}</label>
        {{ form.description }}
      </div>
      <div id="slug" class="audiotracks-edit-row">
        {{ form.slug.errors }}
        <label for="id_slug">{{ form.slug.label }}</label>
        <div class="input-prepend" style="margin-left:30%">
          <span class="audiotracks-edit-current-data add-on">{{ track_url_prefix }}</span>{{ form.slug }}
        </div>
      </div>


     
    </fieldset>
     <p id="save-button">
      <button class="btn btn-primary">{% trans 'Save your changes' %}</button>
      </p>
  </form>
</div>
<div class="audiotracks-form" id="delete-form" align="center">
  <form action="{% url 'confirm_delete_track' track.id %}">
    <p id="delete-button">
    <button class="btn btn-danger">{% trans 'Delete this track' %}</button>
    </p>
  </form>
</div>
{% endif %}
{% endblock %}

webapp/codes/modules/tracks/templates/audiotracks/latest.html
{% extends "audiotracks/mediaelement_base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<div align="center">
<h1>{% trans 'Latest Tracks' %}</h1>
<br/>

<div align="center">
 {% include '_pagination.html' %} 
</div>


 <div class="teams">
  <div class="row">
{% for track in tracks %}
 
     
<div class="col-md-3 col-sm-3 col-xs-6">
                              
                                 <div class="staff">
                                 <div class="pic">
                                    {% if track.image %}
    <img class="track-image" src="{{ track.image.url_200x200 }}" alt="{% trans 'Track Image' %}" />
    {% endif %}
                                 </div>
                                   <div class="track-details">
      <a href="{% url 'track_detail' track.user.username track.slug %}">
        <p class="track-title js-audiotracks-title">
        {% if track.artist %} {{ track.artist }} &#8211; {% endif %}{{ track.title|title }}{% if track.genre %} ({{ track.genre }}){% endif %}
        </p>
      </a>
      <p class="upload-details">
        {% trans 'uploaded by' %}
        {{ track.user.username }}
        {% blocktrans with track.created_at|timesince as track_age %}{{ track_age }} ago{% endblocktrans %}
      </p>
    </div>

     <div class="player-container">
      <audio preload="none">
        <source src="{{ track.audio_file.url }}" type="{{ track.mimetype }}">
      </audio>
    </div>
    <p/>
     <p class="debug-info">Player type: <span class="audio-type"></span></p>

                                
                             
                         </div>
                  </div>
                 <hr/>
                 <hr/>
             


        {%empty %}
    <h4> sorry no tracks available ,login to upload new tracks</h4> 
                      

{% endfor %}
</div>
</div>
</div>




{% endblock %}

    



webapp/codes/modules/tracks/templates/audiotracks/mediaelement_base.html
{% extends "audiotracks/base.html" %}
{% load staticfiles %}

{% block extra_head %}{{ block.super }}<link rel="stylesheet" href="{% static 'tracks/mediaelement-2.8.2/mediaelementplayer.min.css' %}" />{% endblock %}

{% block extra_body %}{{ block.super}}
<script>window.jQuery || document.write('<script src="{% static 'tracks/mediaelement-2.8.2/jquery-1.7.2.min.js' %}"><\/script>')</script>
<script src="{% static 'tracks/mediaelement-2.8.2/mediaelement-and-player.min.js' %}"></script>
<script src="{% url 'player_script' %}"></script>
{% endblock %}



webapp/codes/modules/tracks/templates/audiotracks/user_index.html
{% extends "audiotracks/mediaelement_base.html" %}
{% load i18n %}

{% block content %}
<div align ="center">
<h1>
  {% blocktrans %}Tracks from {{ username }}{% endblocktrans %}
</h1>
<a href="{% url 'tracks_feed' username %}">Podcast feed</a>,
<a href="{% url 'm3u' username %}">m3u playlist</a>
<ul class="audiotracks-list">
{% for track in tracks %}
    {% include "audiotracks/listing_item.html" %}
     <div class="bor"></div>
{% endfor %}
</ul>
</div>

{% include '_pagination.html' %}

{% endblock %}



