webapp/codes/conf/urls.py
from django.conf.urls import include, url,patterns
from django.contrib import admin
import audiotracks

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # Examples:
    # url(r'^$', 'musicapps.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'website.views.index', name='index'),
    url(r'^tuneaudit/', include('tuneaudit.urls', namespace="tuneaudit")),
    url(r'^tuneaudit/', include('registration.urls',namespace="registration")),
    url(r'^tuneaudit/', include('website.urls', namespace="website")),
    url(r'^tuneaudit/', include('tracks.urls', namespace="tracks")),
    #url(r'^tuneaudit/', include('audiotracks.urls', namespace="audiotracks")),
    url(r'^admin/', include(admin.site.urls)),

    url("^music", include("audiotracks.urls")),
    url("^(?P<username>[\w\._-]+)/music", include("audiotracks.urls")),
]

if not settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )

webapp/codes/modules/registration/urls.py
from django.conf.urls import patterns, include, url

from django.views.generic.base import TemplateView

from . import views



from django.contrib import admin
admin.autodiscover()






urlpatterns = [

    url(r'^register/$', views.ta_register, name='registerview'),
    url(r'^confirmed/(?P<activation_key>\w+)/', views.register_confirm),




]






webapp/codes/modules/website/urls.py
from django.conf.urls import patterns, include, url

from django.views.generic.base import TemplateView

from . import views

from views import DisplayRes,DisplayHome,DisplaySorry


from django.contrib import admin
admin.autodiscover()






urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^loggedout/$', views.logout_view, name='logoutview'),
    #url(r'^tunes/$', views.get_tunes, name='tunesview'),
    #url(r'^login/$', views.ta_login, name='loginview'),
    #url(r'^emailentry/$', views.ta_email, name='emailview'),
    url(r'^restricted/', views.home, name='homepage'),
    #url(r'^login/1$', views.ta_login, name='loginview'),


    
    
    

    url(r'^name/$', views.get_name, name='nameview'),

    url(r'^thanks/$', DisplayRes.as_view()),
    url(r'^home/$', DisplayHome.as_view(),name='home'),
    url(r'^sorry/$', DisplaySorry.as_view()),

    #url(r'^user/password/', include(password_change_patterns)),


    #LOGIN
    url(r'^login/$', 'django.contrib.auth.views.login',name="my_login"),


    #--------------------------password reset ---------------------------#
    url(r'^user/password/reset/$', 'django.contrib.auth.views.password_reset', 
        {'post_reset_redirect' : '/tuneaudit/user/password/reset/done/'},
        name='password_reset'),

    url(r'^user/password/reset/done/$',
        'django.contrib.auth.views.password_reset_done'),

    url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'registration/password_reset_confirm.html',
        'post_reset_redirect' : '/tuneaudit/user/password/done/'},
        name='password_reset_confirm'),

   
    url(r'^user/password/done/$', 
        'django.contrib.auth.views.password_reset_complete'),




    

]






webapp/codes/modules/website/models.py
import datetime

from django.db import models

from django.utils import timezone

from django.forms import ModelForm

from django.contrib.auth.models import User




# Create your models here.
class Genre(models.Model):
    genre_name = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __unicode__(self):              # __unicode__ on Python 2
        return self.genre_name
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'      



    def test_was_published_recently_with_old_pubdate(self):
        """
        was_published_recently() should return False for questions whose
        pub_date is older than 1 day.
        """
        time = timezone.now() - datetime.timedelta(days=30)
        old_genre = Genre(pub_date=time)
        self.assertEqual(old_genre.was_published_recently(), False)

    def test_was_published_recently_with_recent_pubdate(self):
        """
        was_published_recently() should return True for questions whose
        pub_date is within the last day.
        """
        time = timezone.now() - datetime.timedelta(hours=1)
        recent_genre = Genre(pub_date=time)
        self.assertEqual(recent_genre.was_published_recently(), True)  


class Choice(models.Model):
    genre = models.ForeignKey(Genre)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):              # __unicode__ on Python 2
        return self.choice_text





#TUNE AUDIT MODELS.
#-------------------------------------------------------------------------------------------------------
class TuneAuditUser(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    nickname = models.CharField(max_length=50)
    email = models.EmailField()
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    
    def __unicode__(self):              # __unicode__ on Python 2
        return self.firstname

#-------------------------------------------------------------------------------------------------------





webapp/codes/modules/website/forms.py
from django import forms
from django.forms import ModelForm
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import TuneAuditUser





class EmailEntryForm(forms.Form):
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder': 'E-mail address'}))

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100)   







class TuneAuditUserForm(ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name','email','username','password'] 



    

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder': 'E-mail address'}))
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')


#clean email field
    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            User._default_manager.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError(' this email already exists in the system please specify another')

#modify save() method so that we can set user.is_active to False when we first create our user
    def save(self, commit=True):        
        user = super(RegistrationForm, self).save(commit=False)

        user.email = self.cleaned_data['email']
        if commit:
            user.is_active = False # not active until he opens activation link
            user.save()

        return user






class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file'
    )


webapp/codes/modules/website/views.py
from django.shortcuts import render
from .models import Genre,Choice
from django.views import generic
from django.utils import timezone
from django.http import HttpResponseRedirect,HttpResponse

from django.shortcuts import get_object_or_404, render, render_to_response
from django.core.urlresolvers import reverse
from .forms import ContactForm,TuneAuditUserForm,LoginForm,RegistrationForm,EmailEntryForm
from django.core.context_processors import csrf
from django.template import RequestContext


from django.core.mail import send_mail
from django.views.generic.base import TemplateView
from django.contrib.auth import authenticate, login ,logout
from django.contrib.auth.models import User

import hashlib, datetime, random

from django.contrib.auth.decorators import login_required






# Create your views here.


@login_required
def home(request):
    return render(request, 'website/home.html')




def index(request):
    return render(request, 'website/index.html')






class DisplayRes(TemplateView):
    template_name = "website/thanks.html"



class DisplayHome(TemplateView):
    template_name = "website/home.html"    

class DisplaySorry(TemplateView):
    template_name = "tuneaudit/sorry.html"          




def logout_view(request):
    logout(request)

    return render(request, 'website/index.html')
   






  








def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ContactForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['kenny.selorm@gmail.com']
            if cc_myself:
                recipients.append(sender)

            send_mail(subject, message, sender, recipients)
            return HttpResponseRedirect('/tuneaudit/thanks/')
            


    # if a GET (or any other method) we'll create a blank form
    else:
        form = ContactForm()

    return render(request, 'tuneaudit/name.html', {'form': form})

webapp/codes/modules/website/templates/website/confirmed.html
<h1> confirmed, login now</h1>

webapp/codes/modules/website/templates/website/emailentry.html
{% extends "website/base.html" %}
{% load staticfiles %}

{% load widget_tweaks %}

{% block title %}Tune Audit-Login{% endblock %}

{% block slider %} {% endblock %}

{% block content %}   
     
          <!-- Register starts -->
            
            <div class="logreg">
               <div class="row">
                  <div class="col-md-12">
                     <div class="logreg-page">
                        <h3>Enter email <span class="color">Tune Audit</span></h3>                        
                        <hr />
                                    <div class="form">
                                      <!-- Register form (not working)-->
                                      <form action="" method="post"   class="form-horizontal">
                                         {% csrf_token %}

                                       <!-- {{ form.as_p }} -->
                                       {{form.errors}}
                                       {{ form.non_field_errors }}
                             
                                    
                                          
                                          <!-- Email -->
                                          {{ form.email.errors }}
                                          <div class="form-group">
                                            <label class="control-label col-md-3"for="id_email">Email</label>
                                            <div class="col-md-9">
                                              {{ form.email|add_class:"form-control"  }}
                                            </div>
                                          </div>
                                                          
                                          
                                    
                                  
                            
                                          <!-- Buttons -->
                                          <div class="form-group">
                                             <!-- Buttons -->
                       <div class="col-md-8 col-md-offset-3">
                        <input type="submit" value="Submit" class="btn btn-default" />
                        <button type="reset" class="btn btn-default">Reset</button>
                            </div>


                                          </div>
                                    </form>
                                 
                                    </div>                           
                     </div>
                  </div>
               </div>
            </div>
            
            <!-- Login ends -->

{% endblock %}



webapp/codes/modules/website/templates/website/expired.html
<h1> expired</h1>

webapp/codes/modules/website/templates/website/home.html
{% extends "website/base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Tune Audit-Login{% endblock %}

{% block slider %} {% endblock %}

{% block content %}   

  		 <div class="row">
  		 	<div class="col-md-3 col-sm-6">
							  
			</div>
							<div class="col-md-3 col-sm-6">
							   <div class="afeature">
								  <div class="afmatter">
									 <i class="fa fa-cloud"></i>
									 <h4><a href="{% url 'upload_track' %}">Upload Track</a></h4>
									 <p>Praesent at tellus porttitor  sagittis. Mauris tempor nulla. Ut tempus interdum mauris vel vehicula. </p>
								  </div>
							   </div>
							</div>
							<div class="col-md-3 col-sm-6">
							   <div class="afeature">
								  <div class="afmatter">
									 <i class="fa fa-user"></i>
									 <h4><a href="{% url 'user_index' user.username %}">{% trans 'Your tracks' %}</a></h4>
									 <p>Praesent at tellus porttitor  sagittis. Mauris tempor nulla. Ut tempus interdum mauris vel vehicula. </p>
								  </div>
							   </div>                        
							</div>
							                   
						 </div>

{% endblock %}






webapp/codes/modules/website/templates/website/index.html
{% extends "website/base.html" %}

{% block navigation %} {% endblock %}

{% block content %}

<div align="center">



 <h1>   <a href="{% url 'audiotracks' %}">Click here to view tunes</a></h1>
     <p>  <h3>   <a href="{% url 'website:homepage' %}" class="da-link"> Upload your work</a></h3> </p>

     {% if user.is_authenticated %}
     <p>  <h3>   <a href="{% url 'website:logoutview' %}" class="da-link">Logout</a></h3> </p>
     {% else %}
          &nbsp;
      {% endif %}
</div>
{% endblock %}

webapp/codes/modules/website/templates/website/login.html
{% extends "website/base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Tune Audit-Login{% endblock %}

{% block slider %} {% endblock %}

{% block content %}   
     <!-- Login starts -->
            
            <div class="logreg">
               <div class="row">
                  <div class="col-md-12">
                     <div class="logreg-page">
                        <h3>Sign In  <span class="color">Tune Audit</span></h3>                        
                        <hr />
                                    <div class="form">
                                      <!-- Login form (not working)-->
                                      <form   action="" method="post"   class="form-horizontal">
                                        {% csrf_token %}
                                          <!-- Username -->
                                          {{form.errors}}
                                       {{ form.non_field_errors }}
                                        {{ form.username.errors }}
                                          <div class="form-group">
                                            <label class="control-label col-md-3" for="id_username">Username</label>
                                            <div class="col-md-9">
                                              
                                                {{ form.username|add_class:"form-control"  }}
                                            </div>
                                          </div>
                                          <!-- Password -->
                                           {{ form.password.errors }}
                                          <div class="form-group">
                                            <label class="control-label col-md-3" for="id_password">Password</label>
                                            <div class="col-md-9">
                                               {{ form.password|add_class:"form-control"  }}
                                            </div>
                                          </div>
                                          <div class="form-group">
                                             <div class="col-md-9 col-md-offset-3">
                                                <label class="checkbox-inline">
                                                <input type="checkbox"> Remember me
                                                </label>
                                             </div>
                                          </div>                                                                               
                                          <!-- Buttons -->
                                          <div class="form-group">
                                             <!-- Buttons -->
											 <div class="col-md-9 col-md-offset-3">
                                            <input type="submit" value="Submit" class="btn btn-default" />
                                            <button type="reset" class="btn btn-default">Reset</button>
											</div>
										</div>  
                                      </form>
									  
                                      <hr />
                                          <div class="lregister">
                                             Don't have Account? <a href="{% url 'registration:registerview' %}">Register</a>|  <a href="{% url 'website:password_reset' %}">Forgotten password?</a>


                                          </div>
                                    </div>                       
                     </div>
                  </div>
               </div>
            </div>
            
            <!-- Login ends -->          
{% endblock %}



webapp/codes/modules/website/templates/website/name.html
<form action="" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}

<div class="fieldWrapper">
    {{ form.subject.errors }}
    <label for="{{ form.subject.id_for_label }}">Email subject:</label>
    {{ form.subject }}
</div>
<div class="fieldWrapper">
    {{ form.message.errors }}
    <label for="{{ form.message.id_for_label }}">Your message:</label>
    {{ form.message }}
</div>
<div class="fieldWrapper">
    {{ form.sender.errors }}
    <label for="{{ form.sender.id_for_label }}">Your email address:</label>
    {{ form.sender }}
</div>
<div class="fieldWrapper">
    {{ form.cc_myself.errors }}
    <label for="{{ form.cc_myself.id_for_label }}">CC yourself?</label>
    {{ form.cc_myself }}
</div>
    <input type="submit" value="Submit" />

</form>

webapp/codes/modules/website/templates/website/sorry.html
<h1>sorry </h1>

webapp/codes/modules/website/templates/website/thanks.html
{% extends "website/base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Tune Audit-Login{% endblock %}
{% block navigation %} {% endblock %}
{% block slider %} {% endblock %}

{% block content %}   
    <h1>sent email successully</h1>
{% endblock %}



